// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello/hello_rest.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("hello/hello_rest.proto", fileDescriptor_385bed7ba72b2139) }

var fileDescriptor_385bed7ba72b2139 = []byte{
	// 53 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x07, 0x93, 0xf1, 0x45, 0xa9, 0xc5, 0x25, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xac, 0x60, 0x91, 0x24, 0x36, 0x30, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xdf, 0xde,
	0x7c, 0x27, 0x00, 0x00, 0x00,
}
